name: cicd
on:
  push:
    branches: [ master ]
    tags: "*"
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build

  deploy-pr:
    name: Deploy Pull Request
    needs: [build]
    if: github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: build
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: |
          aws s3 sync build/. s3://97a79ff-deployments-dev/ui-${{ github.sha }} \
            --delete \
            --acl public-read \
            --cache-control max-age=31536000
      - run: |
          aws s3 cp s3://97a79ff-deployments-dev/ui-${{ github.sha }}/index.html s3://97a79ff-deployments-dev/ui-${{ github.sha }}/index.html \
            --metadata-directive REPLACE \
            --acl public-read \
            --content-type text/html \
            --cache-control max-age=0,no-cache,no-store,must-revalidate

  deploy-dev:
    name: Deploy to Dev
    needs: [build]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: build
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: |
          aws s3 sync build/. s3://97a79ff-deployments-dev/ui \
            --delete \
            --acl public-read \
            --cache-control max-age=31536000
      - run: |
          aws s3 cp s3://97a79ff-deployments-dev/ui/index.html s3://97a79ff-deployments-dev/ui/index.html \
            --metadata-directive REPLACE \
            --acl public-read \
            --content-type text/html \
            --cache-control max-age=0,no-cache,no-store,must-revalidate

  deploy-prod:
    name: Deploy to Production
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: build
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: |
          aws s3 sync build/. s3://97a79ff-deployments-prod/ui \
            --delete \
            --acl public-read \
            --cache-control max-age=31536000
      - run: |
          aws s3 cp s3://97a79ff-deployments-prod/ui/index.html s3://97a79ff-deployments-prod/ui/index.html \
            --metadata-directive REPLACE \
            --acl public-read \
            --content-type text/html \
            --cache-control max-age=0,no-cache,no-store,must-revalidate